import type { Product, Section } from "../../components/CollectionLayout";

const D_TAP = "Choosing automatic sensor taps is a complex decision, critical for a positive, hygienic experience from a designer's vision. Maintenance teams, facility managers, engineers, and contractors prioritize reliability, easy installation, and time efficiency.";
const D_SOAP = "Selecting a soap dispenser is a crucial decision, impacting the overall hygiene experience in public spaces. Maintenance teams, facility managers, engineers, and contractors prioritize reliability, easy installation, and time efficiency.";
const D_FLUSH = "The concealed flush valve provides maximum performance in even the most demanding, high-traffic commercial spaces. Maintenance teams, facility managers, engineers, and contractors prioritize reliability, easy installation, and time efficiency.";

const ph = (code: string): Product => ({
  name: "", desc: "", specs: [], config: [], code, placeholder: true,
});

const TAP_COMPLIANCE = [
  "Chrome surface: pass 24h Acid Salt Spray Test",
  "WRAS",
  "LEED",
  "WELS 3 Ticks",
];
const FLUSH_COMPLIANCE = ["WRAS", "LEED"];

const SOAP_FEATURES = [
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "1 Year Warranty", icon: "🛡" },
];

export const COMPLIANCE = TAP_COMPLIANCE;

export const FEATURES = [
  { label: "Water Saving", icon: "💧" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "1 Year Warranty", icon: "🛡" },
];

export const sections: Section[] = [
  /* ── WASHBASIN ── */
  {
    id: "washbasin",
    title: "Washbasin",
    overline: "Sensor Lavatory Taps",
    products: [
      {
        name: "Lavatory Deck Mounted Tap (H192mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Brass Body",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 130mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Brass Fixing Nut with Screws",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207",
      },
      {
        name: "Lavatory Deck Mounted Tap (Compact)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Deck mounted",
          "Easy installation",
          "Power Supply AC/DC",
          "Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit",
          "Spout reach 106mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Spray Aerator 1.0 lpm / 0.35 gpm Water Flow",
          "Bluetooth functionality",
          "Laser Sensor - Optimized Detection Performance",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207D",
      },
      {
        name: "Lavatory Deck Mounted Tap (H225mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 124mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Bluetooth functionality",
          "Laser Sensor - Optimized Detection Performance",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207F",
      },
      {
        name: "Lavatory Deck Mounted Tap (Reach 146mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 146mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Bluetooth functionality",
          "Laser Sensor - Optimized Detection Performance",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207O",
      },
      {
        name: "Lavatory Deck Mounted Tap (Reach 124mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 124mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Bluetooth functionality",
          "Laser Sensor - Optimized Detection Performance",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207N",
      },
      {
        name: "Lavatory Deck Mounted Tap (Reach 128mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 128mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Spray Aerator 1.0 lpm / 0.35 gpm Water Flow",
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207T",
      },
      ph("F207S"),
      {
        name: "Lavatory Deck Mounted Tap (H235mm, Multi-Finish)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome, Matt Black, or Stainless Steel",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 126mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Laminar Water Flow (no aerator) 1.9 lpm / 0.5 gpm",
          "Brass Fixing Nut with Screws",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F207B",
      },
      {
        name: "Lavatory Deck Mounted Tap (H315mm, Multi-Finish)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome, Matt Black, or Stainless Steel",
          "Deck mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 126mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Laminar Water Flow (no aerator) 1.9 lpm / 0.5 gpm",
          "Brass Fixing Nut with Screws",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap, Angle Valve, Connection Hose)",
        ],
        code: "F208B",
      },
      {
        name: "Lavatory Wall Mounted Tap (Reach 210mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Brass Body",
          "Wall mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 210mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap)",
        ],
        code: "F209",
      },
      {
        name: "Lavatory Wall Mounted Tap (Multi-Finish, Reach 190mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome, Matt Black, or Stainless Steel",
          "Wall mounted",
          "Easy installation",
          "Vandal-resistant",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 190mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Laminar Water Flow (no aerator) 1.0 lpm / 0.22 gpm",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap)",
        ],
        code: "F209B",
      },
      {
        name: "Lavatory Wall Mounted Tap (Round Spout, Reach 195mm)",
        desc: D_TAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Wall mounted",
          "Easy installation",
          "Round Spout Design",
          "Power Supply AC/DC",
          "Hidden Aerator 1.9 lpm / 0.5 gpm",
          "Sensor Unit Hidden",
          "Spout reach 195mm",
          "Max. continuous flow 60 sec",
          "Water ON 0.4 sec / Water OFF 1.5 sec",
          "Infra-Red Sensing Range max 250 mm",
          "Water pressure 0.1 – 0.8MPa static",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Square Spout Design",
          "Laser Sensor - Optimized Detection Performance",
          "Bluetooth functionality",
          "Power Supply AC only",
          "Power Supply DC only",
          "Fittings (Drainer, P-Trap)",
        ],
        code: "F209C",
      },
      ph("F209D"),
    ],
  },

  /* ── SOAP DISPENSERS ── */
  {
    id: "soap-dispensers",
    title: "Soap Dispensers",
    overline: "Automatic Soap Dispensers",
    products: [
      {
        name: "Deck Mounted Soap Dispenser — Top Refill",
        desc: D_SOAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Brass Body",
          "Easy installation",
          "Power Supply AC/DC",
          "Foam Soap",
          "Top Refill of Soap",
          "1 litre Soap Bottle",
          "Soap discharge time 2 sec",
          "Soap discharge 1.5ml/sec at 1000 cps",
          "Foam Soap Viscosity 1000 – 3500 cps",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Liquid Soap",
          "Bluetooth functionality",
          "Power Supply AC only",
        ],
        code: "ASD01",
        compliance: [],
        features: SOAP_FEATURES,
      },
      {
        name: "Deck Mounted Soap Dispenser",
        desc: D_SOAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Brass Body",
          "Easy installation",
          "Power Supply AC/DC",
          "Foam Soap",
          "1 litre Soap Bottle",
          "Sensor Unit Hidden",
          "Soap discharge time 2 sec",
          "Soap discharge 1.5ml/sec at 1000 cps",
          "Foam Soap Viscosity 1000 – 3500 cps",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Liquid Soap",
          "Bluetooth functionality",
          "Power Supply AC only",
        ],
        code: "ASD02",
        compliance: [],
        features: SOAP_FEATURES,
      },
      {
        name: "Wall Mounted Soap Dispenser (Chrome)",
        desc: D_SOAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome",
          "Brass Body",
          "Easy installation",
          "Power Supply AC/DC",
          "Foam Soap",
          "1 litre Soap Bottle",
          "Sensor Unit Hidden",
          "Soap discharge time 2 sec",
          "Soap discharge 1.5ml/sec at 1000 cps",
          "Foam Soap Viscosity 1000 – 3500 cps",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Liquid Soap",
          "Laser Sensor",
          "Bluetooth functionality",
          "Power Supply AC only",
        ],
        code: "ASD10",
        compliance: [],
        features: SOAP_FEATURES,
      },
      {
        name: "Wall Mounted Soap Dispenser (Multi-Finish)",
        desc: D_SOAP,
        specs: [
          "Compact Structure",
          "Finishes Chrome, Matt Black, Stainless Steel",
          "Brass Body",
          "Easy installation",
          "Power Supply AC/DC",
          "Foam Soap",
          "1 litre Soap Bottle",
          "Sensor Unit Hidden",
          "Soap discharge time 2 sec",
          "Soap discharge 1.5ml/sec at 1000 cps",
          "Foam Soap Viscosity 1000 – 3500 cps",
          "Ambient temperature 1 – 55 °C",
        ],
        config: [
          "Liquid Soap",
          "Laser Sensor",
          "Bluetooth functionality",
          "Power Supply AC only",
        ],
        code: "ASD11",
        compliance: [],
        features: SOAP_FEATURES,
      },
    ],
  },

  /* ── WC / URINAL ── */
  {
    id: "wc-urinal",
    title: "WC / Urinal",
    overline: "Concealed Flush Valves",
    products: [
      {
        name: "Concealed WC Flush Valve",
        desc: D_FLUSH,
        specs: [
          "Compact Structure",
          "Finishes Stainless Steel, Matt Black Glass",
          "Manual Override Button",
          "Brass Body with shutoff Valve and Filter",
          "Easy installation with Installation box",
          "Factory Preset Flow Volume 4.5 lpf @ 0.25 MPa",
          "Power Supply AC/DC",
        ],
        config: [
          "Bluetooth functionality",
          "Dual Flush (full/half) only with Bluetooth",
          "Adjustable Flow Volume based on Water Pressure only with Bluetooth",
          "Factory Preset Flow Volume 6.0 lpf @ 0.25 MPa",
          "Power Supply AC only",
          "Power Supply DC only",
        ],
        code: "F231",
        compliance: FLUSH_COMPLIANCE,
      },
      {
        name: "Concealed Urinal Flush Valve",
        desc: D_FLUSH,
        specs: [
          "Compact Structure",
          "Trim Stainless Steel, Matt Black Glass",
          "Manual Override Button",
          "Brass Body with shutoff Valve and Filter",
          "Easy installation with Installation box",
          "Factory Preset Flow Volume 1 lpf @ 0.25 MPa",
          "Power Supply AC/DC",
        ],
        config: [
          "Bluetooth functionality",
          "Adjustable Flow Volume based on Water Pressure only with Bluetooth",
          "Factory Preset Flow Volume 3 lpf @ 0.25 MPa",
          "Power Supply AC only",
          "Power Supply DC only",
        ],
        code: "F230",
        compliance: FLUSH_COMPLIANCE,
      },
    ],
  },
];
