import type { Product, Section } from "../../components/CollectionLayout";

const ph = (code: string): Product => ({
  name: "",
  desc: "",
  specs: [],
  config: [],
  code,
  placeholder: true,
});

const SINK_COMPLIANCE = ["WRAS", "LEED"];
const FAUCET_COMPLIANCE = [
  "Chrome surface: pass 24h Acid Salt Spray Test",
  "WRAS",
  "LEED",
  "WELS 3 Ticks PPP",
];
const SUS_COMPLIANCE = ["WRAS", "LEED", "WELS 3 Ticks PPP"];

export const COMPLIANCE = FAUCET_COMPLIANCE;

export const FEATURES = [
  { label: "Water Saving", icon: "💧" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "3 Year Warranty", icon: "🛡" },
];

const FEAT_5YR = [
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "5 Year Warranty", icon: "🛡" },
];
const FEAT_TM_5YR = [
  { label: "Topmount", icon: "📐" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "5 Year Warranty", icon: "🛡" },
];
const FEAT_TM_3YR = [
  { label: "Topmount", icon: "📐" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "3 Year Warranty", icon: "🛡" },
];
const FEAT_UM_5YR = [
  { label: "Undermount", icon: "📐" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "5 Year Warranty", icon: "🛡" },
];
const FEAT_UM_1YR = [
  { label: "Undermount", icon: "📐" },
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "1 Year Warranty", icon: "🛡" },
];
const FEAT_1YR = [
  { label: "Precision Engineering", icon: "⚙" },
  { label: "Easy Installation", icon: "🔧" },
  { label: "1 Year Warranty", icon: "🛡" },
];

export const sections: Section[] = [
  /* ── KITCHEN SINK ── */
  {
    id: "kitchen-sink",
    title: "Kitchen Sink",
    overline: "Premium Sink Solutions",
    products: [
      {
        name: "Kitchen Sink All-in-One Solution",
        desc: "Revolutionize your kitchen with an integrated sink featuring a durable honeycomb-embossed surface that's highly scratch-resistant. This all-in-one solution includes a sink insert, vegetable rinse sprayer, filtered water dispenser, glass rinse, soap dispenser, temperature display, and cutting board.",
        specs: [
          "Dimension 720 x 460 x 220mm",
          "Stainless Steel 304",
          "Material Thickness 3.0mm, Bowl 0.9mm",
          "Honeycomb embossing enhances scratch & wear resistance",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Kitchen Pull Out Faucet",
          "3 Function Sprayer Head",
          "Progressive Cartridge for Temperature Regulation",
          "ON/OFF Push Diverter",
          "Vegetable Spray, Waterfall, Filter Water",
        ],
        config: [
          "Soap Dispenser",
          "Glass Rinse",
          "2 Insert Sinks",
          "Cutting Board (wood)",
          "Digital Water Temperature and Time Display",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
          "Alternative Color PVD finishes",
          "Brushed Stainless Steel",
        ],
        code: "KHM001-SET",
        compliance: [],
        features: FEAT_TM_3YR,
      },
      {
        name: "Kitchen Quartz Composite Sink",
        desc: "Elevate your kitchen with premium quartz composite sinks—heat-resistant, durable, non-porous, and designed to retain their vibrant color. Offering versatile installation options, these sinks seamlessly blend style with everyday practicality.",
        specs: [
          "Finish Matt Black",
          "Dimension 800 x 480 x 210mm",
          "Quartz Resin (Artificial Stone)",
          "Material Thickness 10 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Cutting Board (wood), Rinse Off Board, Soap Dispenser",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm",
          "Drain Pipe: PP material with Siphon",
        ],
        config: [
          "Alternative colours, shapes, sizes",
        ],
        code: "KQR001",
        compliance: [],
        features: FEAT_TM_5YR,
      },
      {
        name: "Kitchen Sink Top or Undermount (Welded Single Bowl)",
        desc: "Welded Single Bowl Kitchen Sink with Bowl Corner Radius R10 / R25 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin, Nano Coating",
          "Stainless Steel 304",
          "Material Thickness 0.9 - 1.2 mm",
          "Honeycomb embossing enhances scratch & wear resistance (Nano coated)",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 300 ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
        ],
        code: "KH",
        compliance: [],
        features: FEAT_5YR,
      },
      {
        name: "Kitchen Sink Undermount (Welded Double Bowl)",
        desc: "Welded Double Bowl Kitchen Sink with Bowl Corner Radius R10 / R25 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Polished, Nano Coating (PVD)",
          "Stainless Steel 304",
          "Material Thickness 0.9 – 1.2 mm",
          "Honeycomb embossing enhances scratch & wear resistance (Nano coated / PVD)",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connections",
        ],
        config: [
          "Soap Dispenser, 300 ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
        ],
        code: "KH2",
        compliance: [],
        features: FEAT_5YR,
      },
    ],
  },

  /* ── TOP MOUNTED ── */
  {
    id: "top-mounted",
    title: "Top Mounted",
    overline: "Topmount Kitchen Sinks",
    products: [
      {
        name: "Kitchen Sink Top Mount (Single Bowl)",
        desc: "Pressed Single Bowl Kitchen Sink with Bowl Corner Radius ≥ R40 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin",
          "Stainless Steel 304",
          "Material Thickness 0.8 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 0.5 litre, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
          "Available Sizes:",
          "KT4539: 450×390×200mm (R80, Min Cabinet 50cm)",
          "KT4641: 460×410×200mm (R85, Min Cabinet 50cm)",
          "KT4642: 460×420×220mm (R80, Min Cabinet 50cm)",
          "KT4639: 465×395×190mm (R110, Min Cabinet 50cm)",
          "KT4944: 490×440×180mm (R75, Min Cabinet 60cm)",
          "KT5040: 500×400×220mm (R80, Min Cabinet 60cm)",
          "KT5542: 550×420×220mm (R80, Min Cabinet 70cm)",
          "KT5550: 550×500×180mm (R40, Min Cabinet 60cm)",
          "KT5545: 555×455×220mm (R45, Min Cabinet 60cm)",
          "KT6050: 609×509×220mm (R110, Min Cabinet 80cm)",
          "KT6347: 635×475×220mm (R112, Min Cabinet 80cm)",
        ],
        code: "KT",
        compliance: [],
        features: FEAT_TM_5YR,
      },
      {
        name: "Kitchen Sink Top Mount (Double Bowl)",
        desc: "Pressed Double Bowl Kitchen Sink with Bowl Corner Radius ≥ R40 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin",
          "Stainless Steel 304",
          "Material Thickness 0.8 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 300ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
          "Available Sizes:",
          "KT26939: 690×390×220mm (R90, Min Cabinet 80cm)",
          "KT27241: 720×410×220mm (R90, Min Cabinet 80cm)",
          "KT27743: 770×430×220mm (R80, Min Cabinet 90cm)",
          "KT27843: 780×430×220mm (R90, Min Cabinet 90cm)",
          "KT27848: 780×480×180mm (R80, Min Cabinet 90cm)",
          "KT28045: 800×450×210mm (R90, Min Cabinet 90cm)",
          "KT28243: 820×430×210mm (R80, Min Cabinet 90cm)",
          "KT28245: 820×450×200mm (R80, Min Cabinet 90cm)",
          "KT28250: 820×500×180mm (R80, Min Cabinet 90cm)",
          "KT210250: 1020×500×210mm (R80, Min Cabinet 110cm)",
        ],
        code: "KT2",
        compliance: [],
        features: FEAT_TM_5YR,
      },
      {
        name: "Kitchen Sink Top Mount with Drainer Board",
        desc: "Pressed (Welded) Kitchen Sink with Drainer Board. Bowl Corner Radius ≥ R40 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin",
          "Stainless Steel 304",
          "Material Thickness 0.6 - 0.8 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 300ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
          "Alternative Drainboard Design Options",
          "Available Sizes:",
          "KD5848: 585×485×180mm (R80, Min Cabinet 45cm)",
          "KD7643: 760×435×180mm (R75, Min Cabinet 45cm)",
          "KD7848: 780×480×180mm (R80, Min Cabinet 45cm)",
          "KD8050: 800×500×175mm (R80, Min Cabinet 45cm, 0.6mm)",
          "KD8250: 820×500×180mm (R70, Min Cabinet 45cm)",
          "KD8650: 860×500×210mm (R70, Min Cabinet 60cm)",
          "KD9650: 965×500×175mm (R85, Min Cabinet 50cm, 0.7mm)",
        ],
        code: "KD",
        compliance: [],
        features: FEAT_TM_5YR,
      },
    ],
  },

  /* ── UNDERMOUNT ── */
  {
    id: "undermount",
    title: "Undermount",
    overline: "Undermount Kitchen Sinks",
    products: [
      {
        name: "Kitchen Sink Undermount (Single Bowl)",
        desc: "Pressed Single Bowl Kitchen Sink with Bowl Corner Radius ≥ R40 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin",
          "Stainless Steel 304",
          "Material Thickness 0.8 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 300ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
          "Available Sizes:",
          "KU1731: 178×316×120mm (R75, Min Cabinet 40cm)",
          "KU1830: 180×305×120mm (R40, Min Cabinet 40cm)",
          "KU3733: 370×330×180mm (R60, Min Cabinet 50cm)",
          "KU3844: 380×440×190mm (R70, Min Cabinet 50cm)",
          "KU4236: 420×360×190mm (R80, Min Cabinet 50cm)",
          "KU4237: 420×370×180mm (R80, Min Cabinet 50cm)",
          "KU4439: 440×390×180mm (R75, Min Cabinet 50cm)",
          "KU4441: 445×415×180mm (R75, Min Cabinet 50cm)",
          "KU4545: 455×455×200mm (R80, Min Cabinet 60cm)",
          "KU4641: 460×410×200mm (R80, Min Cabinet 60cm)",
          "KU4843: 480×430×180mm (R80, Min Cabinet 60cm)",
          "KU5343: 533×433×200mm (R65, Min Cabinet 60cm)",
          "KU5742: 575×425×200mm (R80, Min Cabinet 70cm)",
          "KU5853: 582×532×240mm (R84, Min Cabinet 70cm)",
          "KU5845: 585×455×230mm (R80, Min Cabinet 70cm)",
          "KU7645: 762×457×228mm (R80, Min Cabinet 90cm)",
          "KU8045: 800×450×240mm (R110, Min Cabinet 90cm)",
        ],
        code: "KU",
        compliance: [],
        features: FEAT_UM_5YR,
      },
      {
        name: "Kitchen Sink Undermount (Double Bowl)",
        desc: "Pressed Double Bowl Kitchen Sink with Bowl Corner Radius ≥ R40 mm. Available in various dimensions.",
        specs: [
          "Available Finishes Brushed, Satin",
          "Stainless Steel 304",
          "Material Thickness 0.8 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 304, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "Soap Dispenser, 300ml, refill from the top",
          "Stainless Steel 304 Wire Basket",
          "Wood Cutting Board",
          "Available Sizes:",
          "KU25841: 585×410×175mm (R75, Min Cabinet 70cm)",
          "KU26745: 670×450×180mm (R80, Min Cabinet 80cm)",
          "KU27845: 785×450×180mm (R75, Min Cabinet 90cm)",
          "KU27945: 796×457×228mm (R80, Min Cabinet 90cm)",
        ],
        code: "KU2",
        compliance: [],
        features: FEAT_UM_5YR,
      },
      {
        name: "Kitchen Sink Undermount (Economy)",
        desc: "Pressed Single Bowl Kitchen Sink in Stainless Steel 201. Available in various dimensions.",
        specs: [
          "Available Finish Electropolished",
          "Stainless Steel 201",
          "Material Thickness 0.4 – 0.7 mm",
          "Overflow hole",
          "Sound Dampening Pad",
          "Noise Dampening Coating",
          "Drainer: Stainless Steel 201, Basket, Cover, Round Size Ø 110mm, 1½\" connection",
          "Drain Pipe: PP material with Siphon, Flexible with 1½\" connection",
        ],
        config: [
          "No Overflow Hole",
          "No Damping Pad",
          "No Noise Damping Coating",
          "Plastic Drainer",
          "Raw Surface Finish",
          "Available Sizes:",
          "KUB423626: 420×360×200mm (SS201, 0.6mm, Min Cabinet 50cm)",
          "KUB454126: 450×410×200mm (SS201, 0.6mm, Min Cabinet 50cm)",
          "KUB483826: 480×380×200mm (SS201, 0.6mm, Min Cabinet 60cm)",
          "KUB574826: 570×480×200mm (SS201, 0.6mm, Min Cabinet 70cm)",
          "KUB343124: 340×310×130mm (SS201, 0.4mm, Min Cabinet 40cm)",
          "KUB483824: 480×380×130mm (SS201, 0.4mm, Min Cabinet 50cm)",
          "KUB443924: 440×390×130mm (SS201, 0.4mm, Min Cabinet 50cm)",
          "KUB503424: 500×340×130mm (SS201, 0.4mm, Min Cabinet 60cm)",
          "KUB593824: 590×380×130mm (SS201, 0.4mm, Min Cabinet 70cm)",
        ],
        code: "KUB",
        compliance: [],
        features: FEAT_UM_1YR,
      },
    ],
  },

  /* ── ACCESSORIES ── */
  {
    id: "accessories",
    title: "Kitchen Accessories",
    overline: "Essentials for Every Kitchen",
    products: [
      {
        name: "Soap Dispenser",
        desc: "Premium soap dispenser for kitchen sink integration.",
        specs: [
          "Head and Pump Stainless Steel",
          "Body ABS/PP/Stainless Steel",
          "Soap bottle PP Plastic (0.3, 0.5 or 1l capacity)",
        ],
        config: [],
        code: "SD",
        compliance: [],
        features: FEAT_1YR,
      },
      {
        name: "Chopping Board",
        desc: "Premium cutting surface designed to match BSC kitchen sinks.",
        specs: [
          "Wood or Bamboo, minimum thickness 18mm",
          "Various dimensions, matching kitchen sinks",
        ],
        config: [],
        code: "CB",
        compliance: [],
        features: FEAT_1YR,
      },
      {
        name: "Wire Rinse Basket",
        desc: "Stainless steel rinse basket for kitchen sink integration.",
        specs: [
          "Stainless Steel 304",
          "Various dimensions, matching kitchen sinks",
        ],
        config: [],
        code: "KA",
        compliance: [],
        features: FEAT_1YR,
      },
    ],
  },

  /* ── MIXER FAUCETS ── */
  {
    id: "mixer-faucets",
    title: "Mixer Faucets",
    overline: "Kitchen Faucets",
    products: [
      {
        name: "Stainless Steel 304 Kitchen Pullout Faucet",
        desc: "Kitchen Faucet Deck mounted with pull-out spray functionality.",
        specs: [
          "Finishes Chrome, Brushed (Stainless Steel)",
          "Stainless Steel 304",
          "Ceramic Cartridge",
          "360° Swivel Spout",
          "Flexible Sprayer with 2 Spray Modes",
          "600mm Connection Hoses",
        ],
        config: [
          "Faucet 1.0 gpm / 3.8 lpm",
          "Fixing Nut with Screws",
          "Fittings (Angle Valves)",
        ],
        code: "FBT065",
        compliance: FAUCET_COMPLIANCE,
      },
      {
        name: "Kitchen Faucet with Pull Out Spray",
        desc: "Kitchen Pullout Faucet with brass construction.",
        specs: [
          "Finishes Chrome",
          "Brass Body",
          "Zinc Handle",
          "Ceramic Cartridge",
          "360° Swivel Spout",
          "Pull Out Sprayer with 2 Spray Modes",
          "600mm Connection Hoses",
        ],
        config: [
          "Faucet 1.0 gpm / 3.8 lpm",
          "Fixing Nut with Screws",
          "Fittings (Angle Valves)",
        ],
        code: "FBT006",
        compliance: FAUCET_COMPLIANCE,
      },
      {
        name: "Kitchen Mixer Faucet with Pull Out Spray (SUS)",
        desc: "SUS Faucet Series — Kitchen Faucets made from Stainless Steel 304.",
        specs: [
          "Finish Brushed",
          "Stainless Steel 304 forged body",
          "35mm Ceramic Cartridge",
          "360° Swivel Spout",
          "Pull Out Sprayer with 2 Spray Modes",
          "600 mm Connection Hoses",
        ],
        config: [
          "Faucet 1.0 gpm / 3.8 lpm",
          "Faucet 0.5 gpm / 1.9 lpm",
          "Fittings (Angle Valves)",
        ],
        code: "S041",
        compliance: SUS_COMPLIANCE,
      },
      ph("S2-1140"),
      ph("S2-1141"),
      {
        name: "Kitchen Mixer Faucet (SUS)",
        desc: "SUS Faucet Series — Kitchen Faucets made from Stainless Steel 304.",
        specs: [
          "Finish Brushed",
          "Stainless Steel 304 forged body",
          "35mm Ceramic Cartridge",
          "360° Swivel Spout",
          "600 mm Connection Hoses",
        ],
        config: [
          "Faucet 1.5 gpm / 3.8 lpm",
          "Fittings (Angle Valves)",
        ],
        code: "S040",
        compliance: SUS_COMPLIANCE,
      },
    ],
  },

  /* ── TAPS (COLD) ── */
  {
    id: "taps-cold",
    title: "Taps (Cold)",
    overline: "Cold Water Kitchen Taps",
    products: [
      {
        name: "Kitchen Tap with Pull Out Spray (SUS)",
        desc: "SUS Faucet Series — Kitchen tap made from Stainless Steel 304 with pull-out spray.",
        specs: [
          "Finish Brushed",
          "Stainless Steel 304 forged body",
          "¼ turn (90°) Ceramic Cartridge",
          "360° Swivel Spout",
          "Pull Out Sprayer with 2 Spray Modes",
        ],
        config: [
          "Faucet 1.0 gpm / 3.8 lpm",
          "Faucet 0.5 gpm / 1.9 lpm",
          "Fittings (Angle Valve, Connection Hose)",
        ],
        code: "S041-C",
        compliance: SUS_COMPLIANCE,
      },
      {
        name: "Kitchen Tap (Cold) Deck Mounted (SUS)",
        desc: "SUS Collection — Kitchen Tap made from Stainless Steel 304.",
        specs: [
          "Finish Brushed",
          "Stainless Steel 304 forged body",
          "¼ turn (90°) Ceramic Cartridge",
          "360° Swivel Spout",
        ],
        config: [
          "Tap 1.0 gpm / 3.8 lpm",
          "Fixing Nut with Screws",
          "Fittings (Angle Valve, Connection Hose)",
        ],
        code: "SUS040-C",
        compliance: SUS_COMPLIANCE,
      },
      {
        name: "Wall Kitchen Tap (Cold) — LINE",
        desc: "LINE Tap Collection — Kitchen taps available in Chrome.",
        specs: [
          "Finishes Chrome",
          "Brass HP59 Body",
          "360° Swivel Spout",
          "Zinc Handle",
          "¼ turn (90°) Ceramic Cartridge",
          "Aerator unrestricted",
        ],
        config: [
          "Tap 3.8 lpm / 1.0 gpm",
        ],
        code: "F042",
        compliance: [
          "Chrome surface: pass 24h Acid Salt Spray Test",
          "Low Lead Brass",
          "WRAS",
          "LEED",
          "WELS 3 Ticks PPP",
        ],
      },
      {
        name: "Kitchen Tap Wall Mounted (Cold) (SUS)",
        desc: "SUS Faucet Series — Wall mounted kitchen tap made from Stainless Steel 304.",
        specs: [
          "Finish Brushed",
          "Stainless Steel 304 forged body",
          "¼ turn (90°) Ceramic Cartridge",
          "360° Swivel Spout",
        ],
        config: [
          "Tap 1.0 gpm / 3.8 lpm",
        ],
        code: "S040-C-W",
        compliance: SUS_COMPLIANCE,
      },
      ph("F008"),
      ph("F009"),
      ph("F010"),
      ph("F011"),
      ph("F012"),
    ],
  },

  /* ── GREASE TRAP ── */
  {
    id: "grease-trap",
    title: "Grease Trap",
    overline: "Waste Management",
    products: [
      {
        name: "Grease Trap Residential Installation",
        desc: "Keep your wastewater system running smoothly with a grease trap (or grease interceptor), expertly designed to capture grease and solids before they enter the disposal system, ensuring efficiency and preventing costly blockages.",
        specs: [
          "Finishes Brushed",
          "Stainless Steel 304, 1mm",
          "Passivation and Pickling for Corrosion Protection",
          "Capacity 13l (3.4gal)",
          "Oil/Grease collect capacity 4l (1gal)",
          "Bib tap for oil discharge",
          "Processing capacity 20l/min (5gal/min)",
          "Includes PP pipe connection inlet/outlet",
        ],
        config: [
          "Capacity with 16, 20, 24 l",
          "Kitchen Packages includes Kitchen Sink, Tap/Faucet, Piping, Fittings and Grease Trap",
        ],
        code: "G300",
        compliance: [],
        features: [
          { label: "Precision Engineering", icon: "⚙" },
          { label: "Easy Installation", icon: "🔧" },
          { label: "3 Year Warranty", icon: "🛡" },
        ],
      },
    ],
  },
];
