import { Droplets, Settings2, Wrench, ShieldCheck } from "lucide-react";
import type { Product, Section } from "../../components/CollectionLayout";

const CONCEALED_FEATURES = [
  { label: "Precision Engineering", icon: Settings2 },
  { label: "Easy Installation", icon: Wrench },
  { label: "3 Year Warranty", icon: ShieldCheck },
];

export const COMPLIANCE = [
  "Chrome surface: pass 24h Acid Salt Spray Test",
  "Matt Black: ASME 112.18.1",
  "WRAS",
  "LEED",
  "WELS 3 Ticks PPP",
];

export const FEATURES = [
  { label: "Water Saving", icon: Droplets },
  { label: "Precision Engineering", icon: Settings2 },
  { label: "Easy Installation", icon: Wrench },
  { label: "3 Year Warranty", icon: ShieldCheck },
];

export const sections: Section[] = [
  /* ── CONCEALED SHOWER VALVES ── */
  {
    id: "concealed-valves",
    title: "Concealed Shower Valves",
    overline: "Concealed Installations",
    products: [
      {
        name: "Concealed Thermostatic with 3 Water Outlets",
        desc: "Transform your shower experience with a stylish thermostatic concealed system featuring three outlets, offering precise temperature control and a wide range of customizable showering options for unmatched comfort and luxury.",
        specs: [
          "Finishes Chrome, PVD Coatings",
          "Thermostatic Cartridge with Vernet Element",
          "DZR Brass Body",
          "Dial Diverter",
          "Rectangular Escutcheon",
          "Concealed Rough In Unit includes level indicator and screw set",
          "Easy Installation",
        ],
        config: [
          "Installation Possibilities:",
          "Ceiling Shower / Hand Shower / Tub Spout",
          "Ceiling Shower / Side Sprays / Tub Spout",
          "Rain Shower with Waterfall",
          "Wall Shower with Waterfall / Tub Spout",
          "Wall Shower with Waterfall / Side Sprays",
          "Wall Overhead Shower / Hand Shower / Tub Spout",
          "Wall Overhead Shower / Side Sprays / Tub Spout",
        ],
        code: "SHST3W",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Concealed Thermostatic with 2 Water Outlets",
        desc: "Upgrade your bathroom with a sleek thermostatic concealed shower system, featuring dual outlets that deliver precise temperature control and a variety of luxurious showering options for the ultimate personalized experience.",
        specs: [
          "Finishes Chrome, PVD Coatings",
          "Thermostatic Cartridge with Vernet Element",
          "DZR Brass Body",
          "Dial or Push Diverter",
          "Round or Rectangular Escutcheon",
          "Concealed Rough In Unit includes level indicator and screw set",
          "Easy Installation",
        ],
        config: [
          "Installation Possibilities:",
          "Ceiling Shower / Tub Spout",
          "Ceiling Shower / Side Sprays",
          "Ceiling Shower / Hand Shower",
          "Wall Shower with Waterfall",
          "Wall Overhead Shower / Tub Spout",
          "Wall Overhead Shower / Side Sprays",
          "Wall Overhead Shower / Hand Shower",
          "Hand Shower / Tub Spout",
          "Hand Shower / Side Sprays",
        ],
        code: "SHST2W",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Concealed 35mm Cartridge with 2 Water Outlets",
        desc: "Enhance your shower with a sleek concealed system featuring two outlets and a single-lever cartridge, offering effortless control and versatile showering options for a perfect blend of style and convenience.",
        specs: [
          "Finishes Chrome, PVD Coatings",
          "35mm Ceramic Cartridge",
          "DZR Brass Body",
          "Dial or Pull Diverter",
          "Round or Rectangular Escutcheon",
          "Concealed Rough In Unit includes level indicator and screw set",
          "Easy Installation",
        ],
        config: [
          "Installation Possibilities:",
          "Ceiling Shower / Tub Spout",
          "Ceiling Shower / Side Sprays",
          "Ceiling Shower / Hand Shower",
          "Wall Shower with Waterfall",
          "Wall Overhead Shower / Tub Spout",
          "Wall Overhead Shower / Side Sprays",
          "Wall Overhead Shower / Hand Shower",
          "Hand Shower / Tub Spout",
          "Hand Shower / Side Sprays",
        ],
        code: "SHSCI2W",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Concealed 35mm Cartridge with 2 Water Outlets",
        desc: "Elevate your shower experience with a sleek concealed system featuring a dual outlet and your choice of a single-lever cartridge or pressure-balanced control for effortless operation and consistent performance.",
        specs: [
          "Finishes Chrome, Matt Black, PVD Coatings",
          "35mm Ceramic Cartridge",
          "DZR Brass Body",
          "Pull Diverter",
          "Round or Rectangular Escutcheon",
          "Easy Installation",
        ],
        config: [
          "HP59 Brass",
          "Pressure Balance Cartridge",
          "Installation Possibilities:",
          "Ceiling Shower / Tub Spout",
          "Ceiling Shower / Hand Shower",
          "Wall Overhead Shower / Tub Spout",
          "Wall Overhead Shower / Hand Shower",
          "Hand Shower / Tub Spout",
        ],
        code: "SHSC2W",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Concealed 35mm Cartridge with 1 Water Outlet",
        desc: "Elevate your shower experience with a sleek concealed system featuring a single outlet and your choice of a single-lever cartridge or pressure-balanced control for effortless operation and consistent performance.",
        specs: [
          "Finishes Chrome, Matt Black, PVD Coatings",
          "35mm Ceramic Cartridge",
          "DZR Brass Body",
          "Pull Diverter",
          "Round or Rectangular Escutcheon",
          "Easy Installation",
        ],
        config: [
          "HP59 Brass",
          "Pressure Balance Cartridge",
          "Installation Possibilities:",
          "Ceiling Shower",
          "Wall Overhead Shower",
          "Hand Shower",
          "Tub Spout",
        ],
        code: "SHS1W",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
    ],
  },

  /* ── SHOWER SOLUTIONS ── */
  {
    id: "shower-solutions",
    title: "Shower Solutions",
    overline: "Exposed Systems",
    products: [
      {
        name: "2-Function Shower System",
        desc: "Upgrade your bathroom with an exposed shower system featuring a progressive cartridge for precise control and a spacious plate designed to conveniently hold your soap and shampoo bottles.",
        specs: [
          "Finishes Chrome, Matt Black",
          "Brass Body with Tray Cover Plate",
          "Progressive Cartridge",
          "Push Button Key Control",
          "Height Adjustable Shower Pipe",
          'Hand Shower 3 function',
          "1.5m Shower Hose",
          'Round 10" Overhead Shower',
        ],
        config: [
          "Hand Shower 2.0 gpm / 7.6 lpm",
          "Overhead Shower 2.5 gpm / 9.5 lpm",
          "PVC Shower Hose",
          "Noise Reducer",
          "Back Check Valves",
          "Extension Pipe 300mm",
        ],
        code: "SHS01",
      },
      {
        name: "3-Function Shower System",
        desc: "Enhance your shower experience with an exposed system featuring a thermostatic cartridge for precise temperature control and push buttons to effortlessly switch between the overhead shower, hand shower, or waterfall tub filler, complete with a spacious shelf for your essentials.",
        specs: [
          "Finishes Chrome, Matt Black",
          "Brass Body with Tray Cover Plate",
          "Thermostatic Cartridge",
          "Push Button Control",
          "Height Adjustable Shower Pipe",
          "3-Function Hand Shower",
          "1.5m Shower Hose",
          "Rectangular Overhead Shower",
          "Sprayer with ON/OFF function",
        ],
        config: [
          "Hand Shower 2.0 gpm / 7.6 lpm",
          "Overhead Shower 2.5 gpm / 9.5 lpm",
          "PVC Shower Hose",
          "Noise Reducer",
          "Back Check Valves",
          "Extension Pipe 300mm",
        ],
        code: "SHS02",
      },
      {
        name: "Multi Function Shower System (Square)",
        desc: "Enhance your shower experience with an exposed system featuring a thermostatic cartridge for precise temperature control and push buttons to effortlessly switch between the overhead shower, hand shower, or waterfall tub filler, complete with a spacious shelf for your essentials.",
        specs: [
          "Finishes Chrome, Matt Black",
          "Brass Body with Tray Cover Plate",
          "Thermostatic Cartridge",
          "Push Button Key Control",
          "Height Adjustable Shower Pipe",
          "Hand Shower 3 function",
          "1.5m Shower Hose",
          "Square Overhead Shower",
          "Sprayer with ON/OFF function",
          "Tub Spout",
        ],
        config: [
          "Sprayer 1.0 gpm / 3.8 lpm",
          "Hand Shower 2.0 gpm / 7.6 lpm",
          "Overhead Shower 2.5 gpm / 9.5 lpm",
          "Rectangular Overhead Shower",
          "PVC Shower Hose",
          "Noise Reducer",
          "Back Check Valves",
          "Extension Pipe 300mm",
        ],
        code: "SHS03",
      },
      {
        name: "Multi Function Shower System (Rectangular)",
        desc: "Enhance your shower experience with an exposed system featuring a thermostatic cartridge for precise temperature control and push buttons to effortlessly switch between the overhead shower, hand shower, or waterfall tub filler, complete with a spacious shelf for your essentials.",
        specs: [
          "Finishes Chrome, Matt Black",
          "Brass Body with Tray Cover Plate",
          "Thermostatic Cartridge",
          "Push Button Key Control",
          "Height Adjustable Shower Pipe",
          "Hand Shower 3 function",
          "1.5m Shower Hose",
          "Rectangular Overhead Shower",
          "Sprayer with ON/OFF function",
          "Tub Spout",
        ],
        config: [
          "Sprayer 1.0 gpm / 3.8 lpm",
          "Hand Shower 2.0 gpm / 7.6 lpm",
          "Overhead Shower 2.5 gpm / 9.5 lpm",
          "Square Overhead Shower",
          "PVC Shower Hose",
          "Noise Reducer",
          "Back Check Valves",
          "Extension Pipe 300mm",
        ],
        code: "SHS04",
      },
      {
        name: "Exposed Shower Solutions",
        desc: "Upgrade your bathroom with a versatile exposed shower system, featuring sleek single-lever control and flexible options for both shower and bath-shower installations, combining style, convenience, and performance.",
        specs: [
          "— Shower System —",
          "Finishes Chrome",
          "HP59 Brass Body",
          "35mm Cartridge",
          "Height Adjustable Shower Pipe",
          "Hand Shower 1 function",
          "1.5m Shower Hose",
          "Rectangular Overhead Shower",
          "Tub Spout",
          "— Shower Mixer —",
          "Hand Shower 1 function",
          "1.5m Shower Hose",
          "Wall Bracket Hand Shower Holder",
          "— Bath Shower Mixer —",
          "Swivel Spout with Diverter",
          "Hand Shower 1 function",
          "1.5m Shower Hose",
          "Wall Bracket Hand Shower Holder",
        ],
        config: [
          "Hand Shower 2.0 gpm / 7.6 lpm",
          "Overhead Shower 2.5 gpm / 9.5 lpm",
          "Sliding Rail",
          "PVC Shower Hose",
          "Noise Reducer",
          "Back Check Valves",
        ],
        code: "SHS05",
      },
    ],
  },

  /* ── SHOWER ACCESSORIES ── */
  {
    id: "shower-accessories",
    title: "Shower Accessories",
    overline: "Accessories & Components",
    products: [
      {
        name: "Overhead Shower",
        desc: "Transform your shower experience with a range of overhead options, whether round, square, or rectangular, available in sizes from compact to large, offering customizable style and coverage to suit any bathroom.",
        specs: [
          "Finishes Chrome, Matt Black, PVD, Brushed",
          "Brass, Stainless Steel, ABS",
          "Faceplate Diameter Ø 150 – 300mm",
          "Faceplate Dimension 200 x 200mm / 300 x 180mm",
        ],
        config: [],
        code: "SHSOH",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Head Shower",
        desc: "Discover the cost-effective alternative to overhead showers with head showers, offering the flexibility to choose from up to three different spray patterns for a personalized and refreshing shower experience.",
        specs: [
          "Finishes Chrome",
          "ABS",
          "Faceplate Diameter Ø 95mm",
          "Faceplate Color",
          "Single or 3 Function Spray Mode",
        ],
        config: [],
        code: "SHSOHS",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Head / Hand Shower Combination",
        desc: "Experience the ultimate in showering with a head shower, complemented by a hand shower offering up to 8 different spray patterns, providing the perfect combination of versatility and indulgence for a truly personalized shower experience.",
        specs: [
          "Finishes Chrome",
          "Faceplate Chrome",
          "Material ABS",
          "Shower Arm",
          "Diverter with Hand Shower Holder",
          "Head Shower Diameter 120mm",
          "Hand Shower Diameter 120mm",
          "1.5m Shower Hose",
        ],
        config: [
          "Flow Restriction 6, 9 or 12 lpm",
          "PVC Shower Hose",
          "Plus Adjustable Wall Bracket",
          "Shower Arm with Hand Shower Holder Only",
          "Shower Arm with Head Shower only",
        ],
        code: "SHSOHHS",
      },
      {
        name: "Hand Shower",
        desc: "Discover a wide range of hand showers, available in small or large, round or rectangular designs, with push or dial function options. The market offers numerous affordable solutions, featuring up to 5 different spray patterns to suit every showering preference.",
        specs: [
          "Finishes Chrome, Matt Black, PVD, White",
          "Faceplate Color Options",
          "Round or Cubical Design",
          "Faceplate Diameter 85 – 130mm",
          "Single Spray Function",
          "Multiple Spray Functions including shut off",
          "Integrated Temperature Display",
          "Dial or Push Activation",
        ],
        config: [],
        code: "SHSHS",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Raiser Rail / Sliding Bar",
        desc: "Enhance your shower or bath-shower experience with a versatile raiser rail, offering flexible height installation to perfectly complement your faucet or seamlessly integrate into a concealed shower system for added convenience and style.",
        specs: [
          "Material Brass / Stainless Steel / ABS",
          "Finishes Chrome, Matt Black, PVD",
          "Flexible Height Assembly",
          "Round Tube Diameter 19 - 25mm",
          "Rectangular Sliding Bar",
          "Fixed Installation Points",
          "Length 560 - 900mm",
        ],
        config: [
          "Soap Dish Holder",
          "Shower Set Packages:",
          "Hand Shower",
          "Sliding Bar",
          "Shower Hose",
          "Soap Dish Holder",
        ],
        code: "SHSRR",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Shower Hose",
        desc: "Upgrade your shower with sleek, stylish hoses available in a variety of colors, featuring reinforced inner liners for long-lasting durability. With a wide range of configurations to choose from, you'll find the perfect solution to fit any budget.",
        specs: [
          "1200, 1750 or 2000mm length",
          "Colour options",
          "Electropolished Stainless-Steel Outer Hose",
          "Smooth PVC Outer Hose",
          "Reinforced Inner Liner",
          "Revolving Conical Nut",
        ],
        config: [],
        code: "SHSHH",
        compliance: ["EN1113", "WRAS", "KTW-BWGL"],
        features: CONCEALED_FEATURES,
      },
      {
        name: "Shower Seat",
        desc: "Enjoy added comfort and convenience with a foldable shower seat, designed to save space while providing sturdy support and a relaxing experience in your shower.",
        specs: [
          "Slim Wall Hung Foldable Shower Seat",
          "Ergonomical Designed Backrest",
          "Silent Folding",
          "Anti Scratch Material (Urea)",
          "No Discoloration",
          "Easy Install",
          "ADA Compliant",
        ],
        config: [],
        code: "SHSFS",
        compliance: [],
        features: CONCEALED_FEATURES,
      },
    ],
  },
];
